# Generated by Django 4.1.6 on 2023-02-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Usuário já cadastrado!'}, help_text='Um nome curto para a sua identificação exclusiva no sistema.', max_length=30, unique=True, verbose_name='Usuário'),
        ),
    ]
