# Generated by Django 4.1.6 on 2023-02-18 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tasks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('start_date_task', models.DateTimeField(help_text='Data/hora em que a tarefa terá sua execução iniciada.', validators=[tasks.models.validate_date], verbose_name='Data de início da tarefa')),
                ('deadline_date', models.DateTimeField(help_text='Data/hora em que a tarefa deve ser feita ou em que ela deve está concluída.', validators=[tasks.models.validate_date], verbose_name='Data prazo')),
                ('date_conclusion', models.DateTimeField(null=True, verbose_name='Data de conclusão')),
                ('startup_date', models.DateTimeField(null=True, verbose_name='Data de inicialização')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('punctuality', models.BooleanField(default=False, verbose_name='Pontualidade')),
                ('start_task', models.BooleanField(default=False, verbose_name='Iniciar tarefa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
