# Generated by Django 4.1.6 on 2023-02-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_date_conclusion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_conclusion',
            field=models.DateTimeField(null=True, verbose_name='Data de conclusão'),
        ),
    ]
